### ISSUE TITLE
micro new helloworld 创建的服务 怎么加入插件和调试代码?

### ISSUE THREAD

**Issue by dili-world** [CleverBamboo/go-micro-examples#2]
`micro new helloworld` 创建的服务 只能`micro run .` 运行，如果自己用 go run main.go 会报错，如何加入go micro 插件 ？

我看micro run .之后 注册到 micro store里面了，但是我想注册到 consul 或 etcd怎么弄？

我试了在 micro new 的main.go里面 改用"github.com/asim/go-micro/v3"创建srv,结果`pb.RegisterHelloworldHandler(service.Server(), new(Helloworld))  `这里提示 不兼容 
```
cannot use service.Server() (type "github.com/asim/go-micro/v3/server".Server) as type "github.com/micro/micro/v3/service/server".Server in argument to helloworld.RegisterHelloworldHandler:
        "github.com/asim/go-micro/v3/server".Server does not implement "github.com/micro/micro/v3/service/server".Server (wrong type for Handle method)
```

而且， micro run . 之后直接就开启后台进程了，如何 直接在代码编辑器里面 debug 代码？

**Comment by Bamboo742** [comment]
不能引用micro的库，参考这个库，https://github.com/microhq/go-plugins

**Comment by Bamboo742** [comment]
调试代码的话，直接用 goland 运行就好了。

**Comment by Bamboo742** [comment]
![image](https://user-images.githubusercontent.com/24216880/118458945-d0d58e80-b72d-11eb-82b2-554dd82fb9da.png)
关键代码示例
